import "dotenv/config";
import { neon } from "@neondatabase/serverless";
import bcrypt from "bcryptjs";
import cors from "cors";
import express from "express";
import jwt from "jsonwebtoken";
import { createHash, randomBytes } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";

const port = Number(process.env.PORT || 4000);
const jwtSecret = process.env.JWT_SECRET || "replace-this-development-secret-before-production";
const databaseUrl = process.env.DATABASE_URL;
const isProduction = process.env.NODE_ENV === "production";
if (isProduction && jwtSecret === "replace-this-development-secret-before-production") throw new Error("JWT_SECRET must be set when NODE_ENV=production.");
if (!databaseUrl) throw new Error("DATABASE_URL must be set to a Neon Postgres connection string.");

const sql = neon(databaseUrl);
function placeholders(statement) { let index = 0; return statement.replace(/\?/g, () => `$${++index}`); }
async function rows(statement, ...parameters) { return sql.query(placeholders(statement), parameters); }
async function one(statement, ...parameters) { return (await rows(statement, ...parameters))[0]; }

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS stations (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, currency_code TEXT NOT NULL DEFAULT 'GHS' CHECK (currency_code = 'GHS'), active_rate_pesewas_per_kg INTEGER NOT NULL DEFAULT 1500 CHECK (active_rate_pesewas_per_kg > 0), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, station_id INTEGER REFERENCES stations(id), role TEXT NOT NULL DEFAULT 'manager', created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS password_reset_tokens (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS password_reset_tokens_expires_at ON password_reset_tokens (expires_at)`,
  `CREATE TABLE IF NOT EXISTS gas_rate_history (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, station_id INTEGER NOT NULL REFERENCES stations(id) ON DELETE CASCADE, rate_pesewas_per_kg INTEGER NOT NULL CHECK (rate_pesewas_per_kg > 0), set_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, effective_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS gas_rate_history_station_effective_at ON gas_rate_history (station_id, effective_at DESC)`,
  `CREATE TABLE IF NOT EXISTS customers (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, station_id INTEGER NOT NULL REFERENCES stations(id) ON DELETE CASCADE, name TEXT NOT NULL, phone TEXT, delivery_address TEXT, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS customers_station_name ON customers (station_id, name)`,
  `CREATE TABLE IF NOT EXISTS sales (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, station_id INTEGER NOT NULL REFERENCES stations(id) ON DELETE CASCADE, customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL, created_by_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT, cylinder_weight_grams INTEGER NOT NULL CHECK (cylinder_weight_grams > 0), quantity INTEGER NOT NULL CHECK (quantity > 0), rate_pesewas_per_kg INTEGER NOT NULL CHECK (rate_pesewas_per_kg > 0), total_pesewas INTEGER NOT NULL CHECK (total_pesewas >= 0), payment_method TEXT NOT NULL CHECK (payment_method IN ('cash', 'mobile_money', 'credit')), delivery_location TEXT, status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('completed', 'voided')), sold_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS sales_station_sold_at ON sales (station_id, sold_at DESC)`,
  `CREATE INDEX IF NOT EXISTS sales_customer_status ON sales (customer_id, status)`,
  `CREATE TABLE IF NOT EXISTS sale_payments (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sale_id INTEGER NOT NULL REFERENCES sales(id) ON DELETE CASCADE, station_id INTEGER NOT NULL REFERENCES stations(id) ON DELETE CASCADE, amount_pesewas INTEGER NOT NULL CHECK (amount_pesewas > 0), method TEXT NOT NULL CHECK (method IN ('cash', 'mobile_money', 'credit_settlement')), reference TEXT, received_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS sale_payments_sale_received_at ON sale_payments (sale_id, received_at DESC)`,
  `CREATE TABLE IF NOT EXISTS inventory_movements (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, station_id INTEGER NOT NULL REFERENCES stations(id) ON DELETE CASCADE, cylinder_weight_grams INTEGER NOT NULL CHECK (cylinder_weight_grams > 0), quantity_change INTEGER NOT NULL CHECK (quantity_change <> 0), movement_type TEXT NOT NULL CHECK (movement_type IN ('opening_stock', 'delivery', 'sale', 'adjustment', 'return')), reference_sale_id INTEGER REFERENCES sales(id) ON DELETE SET NULL, note TEXT, recorded_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL, recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS inventory_movements_station_weight_recorded_at ON inventory_movements (station_id, cylinder_weight_grams, recorded_at DESC)`,
];
let initialization;
function initializeDatabase() {
  return initialization ||= (async () => {
    for (const statement of schemaStatements) await rows(statement);
  })();
}

const app = express();
app.disable("x-powered-by");
const clientOrigins = (process.env.CLIENT_ORIGIN || "http://localhost:5173").split(",").map((origin) => origin.trim().replace(/\/$/, "")).filter(Boolean);
app.use(cors({ origin(origin, callback) { return !origin || clientOrigins.includes(origin) ? callback(null, true) : callback(new Error(`Origin ${origin} is not allowed by CLIENT_ORIGIN.`)); } }));
app.use(express.json({ limit: "16kb" }));
app.use(async (_req, _res, next) => { try { await initializeDatabase(); next(); } catch (error) { next(error); } });

const loginAttempts = new Map();
const loginLimit = 10;
const loginWindowMs = 15 * 60 * 1000;
const publicUser = (user) => ({ id: user.id, name: user.name, email: user.email, stationId: user.station_id, role: user.role, createdAt: user.created_at });
const createToken = (user) => jwt.sign({ sub: String(user.id), email: user.email }, jwtSecret, { expiresIn: "7d" });
const hashResetToken = (token) => createHash("sha256").update(token).digest("hex");

async function sendPasswordResetEmail({ email, name, resetToken }) {
  const clientOrigin = (process.env.CLIENT_ORIGIN || "http://localhost:5173").split(",")[0].trim();
  const resetUrl = new URL("/", clientOrigin);
  resetUrl.searchParams.set("reset_token", resetToken);
  if (!process.env.RESEND_API_KEY) {
    if (isProduction) throw new Error("Password reset email delivery is not configured.");
    return { developmentCode: resetToken };
  }
  const response = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: process.env.RESET_EMAIL_FROM || "GasFlow <onboarding@resend.dev>", to: [email], subject: "Reset your GasFlow password", html: `<p>Hello ${name},</p><p>Use the link below to reset your GasFlow password. It expires in one hour.</p><p><a href="${resetUrl}">Reset password</a></p>` }) });
  if (!response.ok) throw new Error("Password reset email delivery failed.");
  return {};
}

function authenticate(req, res, next) {
  const token = req.get("authorization")?.replace(/^Bearer\s+/i, "");
  if (!token) return res.status(401).json({ error: "Authentication is required." });
  try { req.auth = jwt.verify(token, jwtSecret); return next(); } catch { return res.status(401).json({ error: "Your session has expired. Please sign in again." }); }
}
async function requireStation(req, res, next) {
  try { const user = await one("SELECT id, station_id, role FROM users WHERE id = ?", Number(req.auth.sub)); if (!user?.station_id) return res.status(403).json({ error: "This account is not assigned to a station." }); req.user = user; return next(); } catch (error) { return next(error); }
}
function positiveInteger(value) { const number = Number(value); return Number.isSafeInteger(number) && number > 0 ? number : null; }
function normalizePaymentMethod(value) {
  const method = String(value || "").trim().toLowerCase().replace(/\s*\/\s*/g, "/").replace(/\s+/g, "_");
  if (method === "cash") return "cash";
  if (method === "mobile_money" || method === "momo") return "mobile_money";
  return method === "credit" || method === "credit/debt" || method === "credit_debt" ? "credit" : null;
}
function validateCredentials({ name, email, password }, needsName) {
  const cleanName = typeof name === "string" ? name.trim().replace(/\s+/g, " ") : "";
  const cleanEmail = typeof email === "string" ? email.trim().toLowerCase() : "";
  if (needsName && (cleanName.length < 2 || cleanName.length > 80)) return { error: "Enter a name between 2 and 80 characters." };
  if (!/^\S+@\S+\.\S+$/.test(cleanEmail) || cleanEmail.length > 254) return { error: "Enter a valid work email address." };
  if (typeof password !== "string" || password.length < 8 || password.length > 128) return { error: "Password must be between 8 and 128 characters." };
  return { name: cleanName, email: cleanEmail, password };
}

app.get("/api/health", (_req, res) => res.json({ status: "ok", service: "gasflow-api", database: "postgres" }));
app.post("/api/auth/register", async (req, res, next) => {
  try {
    const input = validateCredentials(req.body || {}, true);
    if (input.error) return res.status(400).json({ error: input.error });
    if (await one("SELECT id FROM users WHERE email = ?", input.email)) return res.status(409).json({ error: "An account already exists for this email." });
    const passwordHash = await bcrypt.hash(input.password, 12);
    const user = await one(`WITH new_station AS (INSERT INTO stations (name) VALUES ($1) RETURNING id), new_user AS (INSERT INTO users (name, email, password_hash, station_id) SELECT $1, $2, $3, id FROM new_station RETURNING *), initial_rate AS (INSERT INTO gas_rate_history (station_id, rate_pesewas_per_kg, set_by_user_id) SELECT new_station.id, 1500, new_user.id FROM new_station CROSS JOIN new_user) SELECT * FROM new_user`, input.name, input.email, passwordHash);
    return res.status(201).json({ token: createToken(user), user: publicUser(user) });
  } catch (error) { return next(error); }
});
app.post("/api/auth/login", async (req, res, next) => {
  const clientKey = req.ip;
  const attempt = loginAttempts.get(clientKey);
  if (attempt && attempt.count >= loginLimit && Date.now() - attempt.startedAt < loginWindowMs) return res.status(429).json({ error: "Too many sign-in attempts. Try again in 15 minutes." });
  try {
    const input = validateCredentials(req.body || {}, false);
    if (input.error) return res.status(400).json({ error: input.error });
    const user = await one("SELECT * FROM users WHERE email = ?", input.email);
    if (!user || !(await bcrypt.compare(input.password, user.password_hash))) { const current = loginAttempts.get(clientKey); loginAttempts.set(clientKey, { count: (current?.count || 0) + 1, startedAt: current?.startedAt || Date.now() }); return res.status(401).json({ error: "Email or password is incorrect." }); }
    loginAttempts.delete(clientKey);
    return res.json({ token: createToken(user), user: publicUser(user) });
  } catch (error) { return next(error); }
});
app.post("/api/auth/request-password-reset", async (req, res, next) => {
  try {
    const email = typeof req.body?.email === "string" ? req.body.email.trim().toLowerCase() : "";
    if (!/^\S+@\S+\.\S+$/.test(email) || email.length > 254) return res.status(400).json({ error: "Enter a valid work email address." });
    const user = await one("SELECT * FROM users WHERE email = ?", email);
    if (!user) return res.json({ message: "If an account exists for that email, a reset link has been sent." });
    const resetToken = randomBytes(32).toString("hex");
    await rows("DELETE FROM password_reset_tokens WHERE user_id = ? OR expires_at <= CURRENT_TIMESTAMP", user.id);
    await rows("INSERT INTO password_reset_tokens (user_id, token_hash, expires_at) VALUES (?, ?, ?)", user.id, hashResetToken(resetToken), new Date(Date.now() + 3600000).toISOString());
    const delivery = await sendPasswordResetEmail({ email: user.email, name: user.name, resetToken });
    return res.json({ message: "If an account exists for that email, a reset link has been sent.", ...(delivery.developmentCode ? { developmentCode: delivery.developmentCode } : {}) });
  } catch (error) { return next(error); }
});
app.post("/api/auth/reset-password", async (req, res, next) => {
  try {
    const token = typeof req.body?.token === "string" ? req.body.token : "";
    const password = req.body?.password;
    if (!token || typeof password !== "string" || password.length < 8 || password.length > 128) return res.status(400).json({ error: "Use a valid reset link and a password between 8 and 128 characters." });
    const resetRecord = await one("SELECT id, user_id FROM password_reset_tokens WHERE token_hash = ? AND expires_at > CURRENT_TIMESTAMP", hashResetToken(token));
    if (!resetRecord) return res.status(400).json({ error: "This reset link is invalid or has expired." });
    const passwordHash = await bcrypt.hash(password, 12);
    await rows("WITH updated AS (UPDATE users SET password_hash = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2 RETURNING id) DELETE FROM password_reset_tokens WHERE user_id IN (SELECT id FROM updated)", passwordHash, resetRecord.user_id);
    return res.json({ message: "Your password has been reset. You can now sign in." });
  } catch (error) { return next(error); }
});
app.get("/api/auth/me", authenticate, async (req, res, next) => { try { const user = await one("SELECT * FROM users WHERE id = ?", Number(req.auth.sub)); return user ? res.json({ user: publicUser(user) }) : res.status(401).json({ error: "This account no longer exists." }); } catch (error) { return next(error); } });
app.patch("/api/auth/me", authenticate, async (req, res, next) => {
  try {
    const user = await one("SELECT * FROM users WHERE id = ?", Number(req.auth.sub));
    if (!user) return res.status(401).json({ error: "This account no longer exists." });
    const name = typeof req.body?.name === "string" ? req.body.name.trim().replace(/\s+/g, " ") : user.name;
    const password = req.body?.password;
    if (name.length < 2 || name.length > 80) return res.status(400).json({ error: "Enter a name between 2 and 80 characters." });
    if (password !== undefined && (typeof password !== "string" || password.length < 8 || password.length > 128)) return res.status(400).json({ error: "Password must be between 8 and 128 characters." });
    const updatedUser = await one("UPDATE users SET name = ?, password_hash = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? RETURNING *", name, password ? await bcrypt.hash(password, 12) : user.password_hash, user.id);
    return res.json({ user: publicUser(updatedUser) });
  } catch (error) { return next(error); }
});
app.get("/api/station", authenticate, requireStation, async (req, res, next) => { try { return res.json({ station: await one("SELECT * FROM stations WHERE id = ?", req.user.station_id) }); } catch (error) { return next(error); } });
app.get("/api/station/rates", authenticate, requireStation, async (req, res, next) => { try { return res.json({ rates: await rows("SELECT gas_rate_history.id, gas_rate_history.rate_pesewas_per_kg, gas_rate_history.effective_at, users.name AS set_by FROM gas_rate_history LEFT JOIN users ON users.id = gas_rate_history.set_by_user_id WHERE gas_rate_history.station_id = ? ORDER BY gas_rate_history.effective_at DESC, gas_rate_history.id DESC", req.user.station_id) }); } catch (error) { return next(error); } });
app.put("/api/station/rate", authenticate, requireStation, async (req, res, next) => {
  try {
    if (req.user.role !== "manager") return res.status(403).json({ error: "Only station managers can update the gas rate." });
    const ratePesewasPerKg = positiveInteger(req.body?.ratePesewasPerKg);
    if (!ratePesewasPerKg || ratePesewasPerKg > 100000) return res.status(400).json({ error: "Enter a valid rate in pesewas per kilogram." });
    await rows("WITH updated AS (UPDATE stations SET active_rate_pesewas_per_kg = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2 RETURNING id) INSERT INTO gas_rate_history (station_id, rate_pesewas_per_kg, set_by_user_id) SELECT id, $1, $3 FROM updated", ratePesewasPerKg, req.user.station_id, req.user.id);
    return res.json({ ratePesewasPerKg });
  } catch (error) { return next(error); }
});
app.get("/api/customers", authenticate, requireStation, async (req, res, next) => { try { const search = typeof req.query.search === "string" ? req.query.search.trim() : ""; return res.json({ customers: await rows("SELECT id, name, phone, delivery_address, notes, created_at, updated_at FROM customers WHERE station_id = ? AND (? = '' OR LOWER(name) LIKE '%' || LOWER(?) || '%') ORDER BY LOWER(name) LIMIT 100", req.user.station_id, search, search) }); } catch (error) { return next(error); } });
app.post("/api/sales", authenticate, requireStation, async (req, res, next) => {
  try {
    const customerName = typeof req.body?.customerName === "string" ? req.body.customerName.trim().replace(/\s+/g, " ") : "";
    const cylinderWeightGrams = positiveInteger(req.body?.cylinderWeightGrams), quantity = positiveInteger(req.body?.quantity), paymentMethod = normalizePaymentMethod(req.body?.paymentMethod), deliveryLocation = typeof req.body?.deliveryLocation === "string" ? req.body.deliveryLocation.trim() : null;
    if (customerName.length < 2 || customerName.length > 120 || !cylinderWeightGrams || !quantity || !paymentMethod) return res.status(400).json({ error: "Provide a customer, cylinder weight, quantity, and payment method." });
    if (cylinderWeightGrams > 100000 || quantity > 1000) return res.status(400).json({ error: "The cylinder weight or quantity is too large." });
    const station = await one("SELECT active_rate_pesewas_per_kg FROM stations WHERE id = ?", req.user.station_id);
    const totalPesewas = (cylinderWeightGrams * station.active_rate_pesewas_per_kg * quantity) / 1000;
    if (!Number.isSafeInteger(totalPesewas)) return res.status(400).json({ error: "The sale total could not be calculated safely." });
    const requestedPaid = req.body?.amountPaidPesewas === undefined ? totalPesewas : positiveInteger(req.body.amountPaidPesewas);
    const amountPaidPesewas = paymentMethod === "credit" ? (requestedPaid || 0) : totalPesewas;
    if (amountPaidPesewas > totalPesewas) return res.status(400).json({ error: "Payment cannot exceed the sale total." });
    const sale = await one(`WITH existing_customer AS (SELECT id FROM customers WHERE station_id = $1 AND LOWER(name) = LOWER($2) ORDER BY id LIMIT 1), new_customer AS (INSERT INTO customers (station_id, name, phone, delivery_address) SELECT $1, $2, $3, $4 WHERE NOT EXISTS (SELECT 1 FROM existing_customer) RETURNING id), customer AS (SELECT id FROM existing_customer UNION ALL SELECT id FROM new_customer LIMIT 1), new_sale AS (INSERT INTO sales (station_id, customer_id, created_by_user_id, cylinder_weight_grams, quantity, rate_pesewas_per_kg, total_pesewas, payment_method, delivery_location) SELECT $1, customer.id, $5, $6, $7, $8, $9, $10, $4 FROM customer RETURNING *), payment AS (INSERT INTO sale_payments (sale_id, station_id, amount_pesewas, method, received_by_user_id) SELECT id, $1, $11, $12, $5 FROM new_sale WHERE $11 > 0), movement AS (INSERT INTO inventory_movements (station_id, cylinder_weight_grams, quantity_change, movement_type, reference_sale_id, recorded_by_user_id) SELECT $1, $6, -$7, 'sale', id, $5 FROM new_sale) SELECT * FROM new_sale`, req.user.station_id, customerName, req.body?.phone?.trim() || null, deliveryLocation, req.user.id, cylinderWeightGrams, quantity, station.active_rate_pesewas_per_kg, totalPesewas, paymentMethod, amountPaidPesewas, paymentMethod === "mobile_money" ? "mobile_money" : "cash");
    return res.status(201).json({ sale });
  } catch (error) { return next(error); }
});
app.get("/api/sales", authenticate, requireStation, async (req, res, next) => { try { const sales = await rows("SELECT sales.id, customers.name AS customer_name, sales.cylinder_weight_grams, sales.quantity, sales.rate_pesewas_per_kg, sales.total_pesewas, sales.payment_method, sales.delivery_location, sales.sold_at, COALESCE(SUM(CASE WHEN sale_payments.method = 'mobile_money' THEN sale_payments.amount_pesewas ELSE 0 END), 0) AS mobile_money_paid_pesewas, COALESCE(SUM(CASE WHEN sale_payments.method IN ('cash', 'credit_settlement') THEN sale_payments.amount_pesewas ELSE 0 END), 0) AS cash_paid_pesewas FROM sales LEFT JOIN customers ON customers.id = sales.customer_id LEFT JOIN sale_payments ON sale_payments.sale_id = sales.id WHERE sales.station_id = ? AND sales.status = 'completed' GROUP BY sales.id, customers.name ORDER BY sales.sold_at DESC, sales.id DESC LIMIT 1000", req.user.station_id); return res.json({ sales }); } catch (error) { return next(error); } });
app.get("/api/debts", authenticate, requireStation, async (req, res, next) => { try { const debts = await rows("SELECT sales.id AS sale_id, customers.id AS customer_id, customers.name AS customer_name, sales.cylinder_weight_grams, sales.quantity, sales.total_pesewas, COALESCE(SUM(sale_payments.amount_pesewas), 0) AS paid_pesewas, sales.sold_at FROM sales JOIN customers ON customers.id = sales.customer_id LEFT JOIN sale_payments ON sale_payments.sale_id = sales.id WHERE sales.station_id = ? AND sales.status = 'completed' GROUP BY sales.id, customers.id, customers.name HAVING sales.total_pesewas > COALESCE(SUM(sale_payments.amount_pesewas), 0) ORDER BY sales.sold_at DESC", req.user.station_id); return res.json({ debts: debts.map((debt) => ({ ...debt, balance_pesewas: debt.total_pesewas - debt.paid_pesewas })) }); } catch (error) { return next(error); } });
app.use((error, _req, res, _next) => { console.error(error); return res.status(500).json({ error: "Something went wrong. Please try again." }); });

export { app, sql };
export default app;
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) app.listen(port, () => console.log(`GasFlow API listening on http://localhost:${port}`));
